### ISSUE TITLE
Error create extention rum

### ISSUE THREAD

**Issue by andreak** [postgrespro/rum#1]
```
andreak=# create extension rum ;
ERROR:  operator <-> already exists

andreak=# select version();
                                                   version                                                   
-------------------------------------------------------------------------------------------------------------
 PostgreSQL 9.6beta1 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 5.3.1-14ubuntu2) 5.3.1 20160413, 64-bit

```

**Comment by select-artur** [comment]
Hello. What extensions did you installed, except rum?
You can see list of the installed extensions by using **\dx** command on **psql**.

**Comment by andreak** [comment]
```
andreak=# \dx
                                     List of installed extensions
    Name    | Version |   Schema   |                            Description                            
------------+---------+------------+-------------------------------------------------------------------
 btree_gin  | 1.0     | public     | support for indexing common datatypes in GIN
 btree_gist | 1.1     | public     | support for indexing common datatypes in GiST
 pg_trgm    | 1.2     | public     | text similarity measurement and index searching based on trigrams
 plpgsql    | 1.0     | pg_catalog | PL/pgSQL procedural language
(4 rows)
```

**Comment by obartunov** [comment]
On Sun, May 29, 2016 at 10:11 PM, Andreas Joseph Krogh <
notifications@github.com> wrote:

> andreak=# \dx
>                                      List of installed extensions
>     Name    | Version |   Schema   |                            Description
> ------------+---------+------------+-------------------------------------------------------------------
>  btree_gin  | 1.0     | public     | support for indexing common datatypes in GIN
>  btree_gist | 1.1     | public     | support for indexing common datatypes in GiST
>
>
bum, btree_gist !

**Comment by akorotkov** [comment]
Yes, it appears that btree_gist also contains "timestamp <-> timestamp".

**Comment by andreak** [comment]
Will this be fixed so that it doesn't clash with btree_gist? I depend upon btree_gist for exclusion-constraints so I really cannot remove it.

**Comment by obartunov** [comment]
On Mon, May 30, 2016 at 9:15 PM, Andreas Joseph Krogh <
notifications@github.com> wrote:

> Will this be fixed so that it doesn't clash with btree_gist? I depend upon
> btree_gist for exclusion-constraints so I really cannot remove it.
>
yes, it should be fixed.

**Comment by andreak** [comment]
Supercool!

**Comment by select-artur** [comment]
Thank you for the issue! Operator <-> was renamed to <=>.

**Comment by andreak** [comment]
Tested it, and it works great now, thanks!
