### ISSUE TITLE
ruminv tests fail under both mac sierra and ubuntu 4.4

### ISSUE THREAD

**Issue by jmscott** [postgrespro/rum#10]
the ruminv regression test is failing identically under both mac sierra and ubuntu4.4

postgres@condor> svn info
Path: .
Working Copy Root Path: /home/postgres/src/postgresql-9.6.1/contrib/rum
URL: https://github.com/postgrespro/rum/trunk
Relative URL: ^/trunk
Repository Root: https://github.com/postgrespro/rum
Repository UUID: 6851b3cf-d1d2-f0c0-02bc-ce57b7db7bff
Revision: 274
Node Kind: directory
Schedule: normal
Last Changed Author: victor.wagner
Last Changed Rev: 273
Last Changed Date: 2017-01-30 02:49:49 -0600 (Mon, 30 Jan 2017)

postgres@condor> cat regression.diffs
*** /home/postgres/src/postgresql-9.6.1/contrib/rum/expected/ruminv.out Fri Feb  3 11:11:33 2017
--- /home/postgres/src/postgresql-9.6.1/contrib/rum/results/ruminv.out  Fri Feb  3 11:12:09 2017
***************
*** 10,22 ****
  INSERT INTO test_invrum VALUES ('(a|b)&(c|d)'::tsquery);
  INSERT INTO test_invrum VALUES ('!a'::tsquery);
  SELECT * FROM test_invrum WHERE q @@ ''::tsvector;
!        q
! ----------------
!  !( 'a' | 'b' )
!  !( 'a' & 'b' )
!  !'a' | 'b'
!  !'a'
! (4 rows)

  SELECT * FROM test_invrum WHERE q @@ 'a'::tsvector;
         q
--- 10,18 ----
  INSERT INTO test_invrum VALUES ('(a|b)&(c|d)'::tsquery);
  INSERT INTO test_invrum VALUES ('!a'::tsquery);
  SELECT * FROM test_invrum WHERE q @@ ''::tsvector;
!  q
! ---
! (0 rows)

  SELECT * FROM test_invrum WHERE q @@ 'a'::tsvector;
         q

======================================================================

**Comment by select-artur** [comment]
Hello, John.
The test was fixed because of the commit for PostgreSQL 9.6 [2dfc12647138deadabfc32123692021b7dd9a94f](https://git.postgresql.org/gitweb/?p=postgresql.git;a=commitdiff;h=2dfc12647138deadabfc32123692021b7dd9a94f)

If you have older version of PostgreSQL you can use [release 0.1](https://github.com/postgrespro/rum/releases/tag/0.1). It is not so far from master.
