### ISSUE TITLE
Ошибка: could not load library "/usr/pgsql-14/lib/rum.so" при выполнении create extension

### ISSUE THREAD

**Issue by xinferum** [postgrespro/rum#103]
Добрый день.
Я выполняю сборку свежей версии rum из ветки master и столкнулся с проблемой при попытке выполнить create extension:
```
=# create extension rum;
ERROR:  58P01: could not load library "/usr/pgsql-14/lib/rum.so": /usr/pgsql-14/lib/rum.so: undefined symbol: postgresql_sort__done_semaphore
LOCATION:  internal_load_library, dfmgr.c:248
````
Данная проблема наблюдается в CentOS 8 (CentOS Linux release 8.5.2111).
В ОС CentOS 7, Ubuntu 18.04 и Ubuntu 20.04 подобной проблемы нет и все работает.
Версия PostgreSQL - 14.1

На текущий момент удалось решить только указав версию 1.3.9 в команде:
```
git clone https://github.com/postgrespro/rum --branch 1.3.9  --single-branch
```

**Comment by sgrinko** [comment]
Подтверждаю.
Я столкнулся с точно такой же проблемой при использовании RUM в докер-контейнере.
Также смог решить проблему только лишь указав версию 1.3.9 в команде:

`git clone https://github.com/postgrespro/rum --branch 1.3.9  --single-branch`

Dockerfile по сборке контейнера здесь: 
`https://github.com/sgrinko/docker-postgres/tree/master/14/docker-postgres`

Я использовал образ `FROM postgres:14.1`  это debian-slim в исходнике
Проявляется на всех используемых мной версиях: 14, 13, 12

**Comment by sgrinko** [comment]
Проверил последний release 1.3.10 на докер контейнере https://github.com/sgrinko/docker-postgres
(образ FROM postgres:14.3 это debian-slim в исходнике)

Компиляция проходит без проблем, но при выполнении команды:
CREATE EXTENSION rum;
ERROR:  could not load library "/usr/lib/postgresql/14/lib/rum.so": /usr/lib/postgresql/14/lib/rum.so: undefined symbol: postgresql_sort__done_semaphore
********** Error **********

ERROR: could not load library "/usr/lib/postgresql/14/lib/rum.so": /usr/lib/postgresql/14/lib/rum.so: undefined symbol: postgresql_sort__done_semaphore
SQL state: 58P01

**Comment by pashkinelfe** [comment]
#108 has been fixed. Please check if #103 is fixed too. If not please let m know.

**Comment by sgrinko** [comment]
Спасибо! Теперь всё  в порядке.
Thank you! Now everything is all right.
