### ISSUE TITLE
Error during RUM installation

### ISSUE THREAD

**Issue by za-arthur** [postgrespro/rum#11]
Here is the messages:
`/usr/bin/mkdir -p '/home/artur/progs/pg9.6/lib/postgresql'
/usr/bin/mkdir -p '/home/artur/progs/pg9.6/share/postgresql/extension'
/usr/bin/mkdir -p '/home/artur/progs/pg9.6/share/postgresql/extension'
/usr/bin/install -c -m 755  rum.so '/home/artur/progs/pg9.6/lib/postgresql/rum.so'
/usr/bin/install -c -m 644 .//src/rum.h .//src/rumsort.h '/home/artur/progs/pg9.6/include/server/'
/usr/bin/install: указанная цель '/home/artur/progs/pg9.6/include/server/' не является каталогом: Нет такого файла или каталога
make: *** [Makefile:37: installincludes] Ошибка 1`

I don't have `/home/artur/progs/pg9.6/include/server/` directory. But I have `/home/artur/progs/pg9.6/include/postgresql/server/`.
This error came from 85a42919ed1d6d21ae3cf49143be7276985c0a99

**Comment by akorotkov** [comment]
Fixed by 85566a73.
