### ISSUE TITLE
warning on var totalCount compile on mac venture clang

### ISSUE THREAD

**Issue by jmscott** [postgrespro/rum#117]
just a heads up.

compile under mac venture clang gives this warning:

     src/rumdatapage.c:1063:8: warning: variable 'totalCount' set but not used [-Wunused-but-set-variable]
        int                     totalCount = 0;

the warning appears to be incorrect, as totalCount is incremented in scope at lines: 1103, 1115, 1137, 1152.
no sure what's up.

the compiler version is Apple clang version 14.0.3 (clang-1403.0.22.14.1) and compile core pg15.3 with no issues.  the ventura version is Darwin tmonk 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:17 PST 2023; root:xnu-8796.101.5~3/RELEASE_X86_64 x86_64 i386 Darwin.

**Comment by sokolcati** [comment]
Thanks for reporting.
The variable has been removed in [this commit](https://github.com/postgrespro/rum/commit/e6ba1addec6eb598feda94da9e3a1a4de56b1e3a).
