### ISSUE TITLE
Weights?

### ISSUE THREAD

**Issue by jimfulton** [postgrespro/rum#12]
ts_rank and ts_rank_cd let you supply weights for text from different sources (A, B, C, and D).

How does RUM handle text from different sources? Does it treat the sources as the same? Does it use built-in weights? Or is there a way to supply weights?

**Comment by za-arthur** [comment]
RUM has different operator for ranking `<=>`. For example:
```sql
SELECT t, a <=> to_tsquery('english', 'beautiful | place') AS rank
    FROM test_rum
    WHERE a @@ to_tsquery('english', 'beautiful | place')
    ORDER BY a <=> to_tsquery('english', 'beautiful | place');
                t                |   rank
---------------------------------+-----------
 The situation is most beautiful | 0.0303964
 It is a beautiful               | 0.0303964
 It looks like a beautiful place | 0.0607927
(3 rows)
```
This operator uses same sources: A, B, C, and D. It has default weights: {0.1, 0.2, 0.4, 1.0}; same as ts_rank and ts_rank_cd. But in current version of RUM you cant supply custom weights.

But you can use ts_rank and ts_rank_cd functions too. But they will be slower than `<=>`.
Do you have any error with this functions?

**Comment by jimfulton** [comment]
No, I don't have an error, I was just wondering if/how weights are used.  You answered my question. Thanks.

**Comment by jimfulton** [comment]
Oh, I didn't try ts_rank/ts_rank_cd because the reason I'm using RUM is to get the faster ranking.

**Comment by za-arthur** [comment]
Yes! They definitely will be slower than RUM's ranking operator.
