### ISSUE TITLE
Index with jsonb and int8?

### ISSUE THREAD

**Issue by mahdiyari** [postgrespro/rum#122]
I have read that rum can help with my problem but I can't actually see how.

I'm trying to create a `jsonb_path_ops` GIN index on a JSONB field and be able to also have sorting by another int8 column. I read that RUM can help with soring in multi column GIN indexes but I guess that wasn't including jsonb since I wasn't able to create an index or find any information.

Sorry, I had to ask somewhere.

**Comment by sokolcati** [comment]
I have collected places with useful information about working with the RUM-index.
- documentation: https://postgrespro.com/docs/enterprise/16/rum
- more details + usage examples: https://habr.com/ru/companies/postgrespro/articles/343488/
- the article is old, but it explains in which cases which index (GIN/RUM) is more profitable: https://habr.com/ru/articles/443368/

**Comment by mahdiyari** [comment]
Thank you.
