### ISSUE TITLE
PostgreSQL 17 support

### ISSUE THREAD

**Issue by devrimgunduz** [postgrespro/rum#127]
Hi,

1.3.13 fails to build against PostgreSQL 17. v17 beta2 is already out. Can you please take a look? 

Thanks, Devrim

> /usr/bin/clang -Wno-ignored-attributes -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-unused-command-line-argument -Wno-compound-token-split-by-macro -Wno-format-truncation -O2  -I. -I./ -I/usr/pgsql-17/include/server -I/usr/pgsql-17/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2 -DWITH_GZFILEOP  -I/usr/include -flto=thin -emit-llvm -c -o src/rumget.bc src/rumget.c
src/ruminsert.c: In function ‘rumHeapTupleBulkInsert’:
src/ruminsert.c:533:51: warning: declaration of ‘attr’ shadows a previous local [-Wshadow=compatible-local]
  533 |                                 Form_pg_attribute attr = RumTupleDescAttr(
      |                                                   ^~~~
src/ruminsert.c:505:27: note: shadowed declaration is here
  505 |         Form_pg_attribute attr = buildstate->rumstate.addAttrs[attnum - 1];
      |                           ^~~~
/usr/bin/clang -Wno-ignored-attributes -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-unused-command-line-argument -Wno-compound-token-split-by-macro -Wno-format-truncation -O2  -I. -I./ -I/usr/pgsql-17/include/server -I/usr/pgsql-17/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2 -DWITH_GZFILEOP  -I/usr/include -flto=thin -emit-llvm -c -o src/ruminsert.bc src/ruminsert.c
src/rumget.c: In function ‘startScanEntry’:
src/rumget.c:635:41: warning: declaration of ‘page’ shadows a previous local [-Wshadow=compatible-local]
  635 |                         Page            page;
      |                                         ^~~~
src/rumget.c:548:25: note: shadowed declaration is here
  548 |         Page            page;
      |                         ^~~~
src/rumget.c: In function ‘entryGetNextItemList’:
src/rumget.c:1054:33: warning: declaration of ‘page’ shadows a previous local [-Wshadow=compatible-local]
 1054 |                 Page            page;
      |                                 ^~~~
src/rumget.c:986:25: note: shadowed declaration is here
  986 |         Page            page;
      |                         ^~~~
/usr/bin/clang -Wno-ignored-attributes -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-unused-command-line-argument -Wno-compound-token-split-by-macro -Wno-format-truncation -O2  -I. -I./ -I/usr/pgsql-17/include/server -I/usr/pgsql-17/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2 -DWITH_GZFILEOP  -I/usr/include -flto=thin -emit-llvm -c -o src/rumscan.bc src/rumscan.c
/usr/bin/clang -Wno-ignored-attributes -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-unused-command-line-argument -Wno-compound-token-split-by-macro -Wno-format-truncation -O2  -I. -I./ -I/usr/pgsql-17/include/server -I/usr/pgsql-17/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2 -DWITH_GZFILEOP  -I/usr/include -flto=thin -emit-llvm -c -o src/rumutil.bc src/rumutil.c
/usr/bin/clang -Wno-ignored-attributes -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-unused-command-line-argument -Wno-compound-token-split-by-macro -Wno-format-truncation -O2  -I. -I./ -I/usr/pgsql-17/include/server -I/usr/pgsql-17/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2 -DWITH_GZFILEOP  -I/usr/include -flto=thin -emit-llvm -c -o src/rumvacuum.bc src/rumvacuum.c
/usr/bin/clang -Wno-ignored-attributes -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-unused-command-line-argument -Wno-compound-token-split-by-macro -Wno-format-truncation -O2  -I. -I./ -I/usr/pgsql-17/include/server -I/usr/pgsql-17/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2 -DWITH_GZFILEOP  -I/usr/include -flto=thin -emit-llvm -c -o src/rumvalidate.bc src/rumvalidate.c
src/rumsort.c:496:47: error: too few arguments to function call, expected 4, have 3
  496 |         tuplesort_puttuple_common(state, &stup, false);
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~                    ^
/usr/pgsql-17/include/server/utils/tuplesort.h:379:13: note: 'tuplesort_puttuple_common' declared here
  379 | extern void tuplesort_puttuple_common(Tuplesortstate *state,
      |             ^                         ~~~~~~~~~~~~~~~~~~~~~~
  380 |                                                                           SortTuple *tuple, bool useAbbrev,
      |                                                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  381 |                                                                           Size tuplen);
      |                                                                           ~~~~~~~~~~~
src/rumsort.c:514:47: error: too few arguments to function call, expected 4, have 3
  514 |         tuplesort_puttuple_common(state, &stup, false);
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~                    ^
/usr/pgsql-17/include/server/utils/tuplesort.h:379:13: note: 'tuplesort_puttuple_common' declared here
  379 | extern void tuplesort_puttuple_common(Tuplesortstate *state,
      |             ^                         ~~~~~~~~~~~~~~~~~~~~~~
  380 |                                                                           SortTuple *tuple, bool useAbbrev,
      |                                                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  381 |                                                                           Size tuplen);
      |                                                                           ~~~~~~~~~~~
2 errors generated.
make[1]: *** [/usr/pgsql-17/lib/pgxs/src/makefiles/../../src/Makefile.global:1085: src/rumsort.bc] Error 1
make[1]: *** Waiting for unfinished jobs....
src/rumsort.c: In function ‘rum_tuplesort_putrum’:
src/rumsort.c:496:9: error: too few arguments to function ‘tuplesort_puttuple_common’
  496 |         tuplesort_puttuple_common(state, &stup, false);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/pgsql-17/include/server/nodes/execnodes.h:49,
                 from /usr/pgsql-17/include/server/executor/execdesc.h:18,
                 from /usr/pgsql-17/include/server/executor/executor.h:17,
                 from src/rumsort.c:23:
/usr/pgsql-17/include/server/utils/tuplesort.h:379:13: note: declared here
  379 | extern void tuplesort_puttuple_common(Tuplesortstate *state,
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~
src/rumsort.c: In function ‘rum_tuplesort_putrumitem’:
src/rumsort.c:514:9: error: too few arguments to function ‘tuplesort_puttuple_common’
  514 |         tuplesort_puttuple_common(state, &stup, false);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~
/usr/pgsql-17/include/server/utils/tuplesort.h:379:13: note: declared here
  379 | extern void tuplesort_puttuple_common(Tuplesortstate *state,
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~
make[1]: *** [<builtin>: src/rumsort.o] Error 1

**Comment by devrimgunduz** [comment]
ping.

**Comment by devrimgunduz** [comment]
ping

**Comment by Florents-Tselai** [comment]
I stumbled upon this during an upgrade to 17, 
Opened a pr #130 (also a similar pr already in #129) .
Maybe someone from postgrespro can have a look ?

**Comment by DorukSega** [comment]
Can confirm same issues on nixos while building with postgresql version 17, 
hopefully this pr is merged soon https://github.com/postgrespro/rum/pull/129

**Comment by sokolcati** [comment]
Thank you for your attention and concern.
The issue has been resolved properly. See the [commit.](https://github.com/postgrespro/rum/commit/cb1edffc57736cd2a4455f8d0feab0d69928da25)

Thanks for waiting while we edited pull request #129.
May success attend you! 
I hope that your vigilance towards rum will continue in the future.

**Comment by Florents-Tselai** [comment]
Beautiful! Thank you!

**Comment by devrimgunduz** [comment]
@sokolcati Thanks! Can you please release a new version so that I can update the RPMs?

Thanks!

**Comment by DorukSega** [comment]
Thanks for the merge!

**Comment by sokolcati** [comment]
@devrimgunduz OK!
[Tag 1.3.14](https://github.com/postgrespro/rum/releases/tag/1.3.14)  is released now.
