### ISSUE TITLE
Have it as a part of Postgres core distribution?

### ISSUE THREAD

**Issue by NikolayS** [postgrespro/rum#14]
Hi, 
what is the current status of this project and how soon it might be included in the Postgres core?

I've just had a chat with Amazon RDS support, and while they have a pretty long list of already supported Postgres extensions, they say that it's pretty hard for them to include contribs written in C (hehe), so for large number of Postgres users living in clouds (RDS, Heroku and now GCP) the only way to use RUM is to have it as a part of Postgres.

**Comment by za-arthur** [comment]
Hello,
RUM is in development state now. I don't believe that it could be included in the PostgreSQL core in the near future.
RUM was started as a patch for GIN several years ago actually. But PostgreSQL's hackers didn't reach agreement about architecture of new changes. And so RUM is an extension now.

**Comment by NikolayS** [comment]
Ok but what if it will be an extension distributed with -contribs standard
package?

It's a pity that you guys currently don't have plans to attack -hackers
with new proposal. As I've said, a lot of users cannot compare le C
extensions, they need packaging (and ideally, postgres-contribs, not a
separate package).

**Comment by NikolayS** [comment]
*compile a C extension

**Comment by obartunov** [comment]
On Wed, Apr 19, 2017 at 6:47 PM, Nikolay <notifications@github.com> wrote:
> Ok but what if it will be an extension distributed with -contribs standard
> package?
>
> It's a pity that you guys currently don't have plans to attack -hackers
> with new proposal. As I've said, a lot of users cannot compare le C
> extensions, they need packaging (and ideally, postgres-contribs, not a
> separate package).

We don't have enough resources to convince hackers right now. Also, we
are waiting for the two new big features - better  custom WAL format
and supports of arrays, hopefully in a couple of weeks.  Notice, today
we released supports of many built-in data types. After that we'll
need somebody's help to write docs and only then we could start
discussion in -hackers.


>
