### ISSUE TITLE
Autovacuum after large update, with active RUM index crashes postgres 

### ISSUE THREAD

**Issue by poppingtonic** [postgrespro/rum#19]
table with 160k records

```
UPDATE {table_name} SET {document}=data.{document} FROM
(VALUES %s) AS data ({document}, id)
WHERE {table_name}.id=data.id;

UPDATE {table_name} set {document_vector}=(select to_tsvector({document}));

CREATE INDEX {table_name}_rum_index
ON {table_name} USING RUM ({document_vector} rum_tsvector_ops);

```
After this set of queries, the autovacuum consumes all available memory before it crashes.

![screenshot from 2017-05-30 10-41-09](https://cloud.githubusercontent.com/assets/5781617/26572924/77d9390a-4524-11e7-9afc-57adde5f721b.png)

**Comment by za-arthur** [comment]
Thank you for the issue! Will check.

**Comment by za-arthur** [comment]
Can you provide a backtrace please?

**Comment by poppingtonic** [comment]
I took too long to get a backtrace, since my machine would lock up. Glad you reproduced it.

**Comment by za-arthur** [comment]
I fixed the bug. Can you check it?

**Comment by poppingtonic** [comment]
Nice work! I ran it while watching htop, and autovacuum topped out at 5% memory right before it stopped.

**Comment by za-arthur** [comment]
Great!
