### ISSUE TITLE
can't compile 

### ISSUE THREAD

**Issue by normandie199** [postgrespro/rum#21]
on ubuntu16.04, i can't compile rum , please help!
![image](https://user-images.githubusercontent.com/13691976/29154855-060d886a-7dca-11e7-905e-4556fd685e1b.png)

**Comment by za-arthur** [comment]
`RUM` requires only PostgreSQL 9.6 and newer. It seems you have older version.

**Comment by akorotkov** [comment]
Hmm... From command line it seems like PostgreSQL 9.6...
@normandie199, could you please show your `pg_config` output?
Also could you attach `/usr/include/postgresql/9.6/server/tsearch/ts_utils.h` file if it exists?

**Comment by romalin99** [comment]
![image](https://user-images.githubusercontent.com/6870144/29304252-a9935c1e-81c4-11e7-8362-b392f55a7473.png)

**Comment by romalin99** [comment]
![image](https://user-images.githubusercontent.com/6870144/29304274-be1161e0-81c4-11e7-90c4-de51eb19ed4e.png)

**Comment by romalin99** [comment]
yet ,I can't compile rum project !

**Comment by za-arthur** [comment]
Can you show result of the query?
```
select version();
```

**Comment by za-arthur** [comment]
It seems the problem was solved.
