### ISSUE TITLE
Missing rumfast.h - trying to compile on windows using Visual Studio

### ISSUE THREAD

**Issue by pholly** [postgrespro/rum#22]
Hi,

The src file `rumfast.c` includes `rumfast.h` but that file is not in the src directory and I get compile errors that `RumTupleCollector` is not defined.

I was able to compile it on Linux so I don't know if I just need to somehow force my windows compiler to ignore the error?

Thanks,
Philip

**Comment by za-arthur** [comment]
Hello,

You can ignore the error. Or you can delete `rumfast.c` on your local copy of the repository for a while. 
`rumfast.c` isn't used anymore. It was used to implement fast update feature. I will remove the file soon.

Thank you for the issue!

**Comment by pholly** [comment]
Thanks!

By the way, I sent an email yesterday to sales asking for a trial download
and license info for Enterprise Pro for Windows. I'm in USA so your office
was probably closed.

If there's any way you could speed up the process for us that would be
great!

**Comment by za-arthur** [comment]
I removed rumfast.c.

Yes, it was too late hour here probably. It is weekends now. So sales department will answer and will give a trial installation on Monday. There are no problems with giving trials usually.
