### ISSUE TITLE
Select count number of search results performance

### ISSUE THREAD

**Issue by pholly** [postgrespro/rum#25]
Postgres 9.6.4
Windows Server 2016

I am trying to get total number of search results. I used a windows function `count(id) OVER() as count` in my search query select clause and that seemed to have caused documents to be loaded into memory instead of just RUM indexes being hit.

I also tried `select count(*) from code_docs where tsv_natural @@ $1` ($1 being a tsquery).

Any way to get count of search results and still only hit the rum indexes?

**Comment by akorotkov** [comment]
Unfortunately it's a PostgreSQL limitation, which is hard to fix within extension.
However, could you try this patch?
https://www.postgresql.org/message-id/239a8955-c0fc-f506-026d-c837e86c827b@postgrespro.ru
I doubt it would work with window function, but it should work for `select count(*) from code_docs where tsv_natural @@ $1`.
If patch will help you, please share your feedback on mailing list.

**Comment by pholly** [comment]
Wow. You're really pioneering PostgresSQL full text search!

We rely on counts for paging and for facets using group bys. We've overcome
most, if not all, of all of PostgresSQL's full text search limitations, but
not being able to get counts in a reasonable time is a dealbreaker. After
further consideration, we will go back to ElasticSearch for our text search
needs but use PostgresSQL as our single source of truth.

Thanks again for your contributions and your timely responses. I'm new to
the PostgresSQL community and you've made it a welcoming place.

Philip

**Comment by za-arthur** [comment]
Unfortunately `RUM` cannot support index scan for `select count(*)` expressions.
I close the issue.
