### ISSUE TITLE
fatal error: sys/sdt.h: No such file or directory

### ISSUE THREAD

**Issue by gzliudan** [postgrespro/rum#27]
Enviroment: CentOS 7.4, Postgres 10.0

export PATH=/usr/pgsql-10/bin:$PATH
git clone https://github.com/postgrespro/rum
cd rum
make USE_PGXS=1

gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -DLINUX_OOM_SCORE_ADJ=0 -fPIC -I. -I./ -I/usr/pgsql-10/include/server -I/usr/pgsql-10/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o src/rumsort.o src/rumsort.c
In file included from src/rumsort.c:138:0:
/usr/pgsql-10/include/server/utils/probes.h:10:21: fatal error: sys/sdt.h: No such file or directory
 #include <sys/sdt.h>
                     ^
compilation terminated.

**Comment by za-arthur** [comment]
Hello,
Thank you for the issue!

I can't reproduce it on same CentOS 7.4 and PostgreSQL 10.0. It seems you need the **systemtap-sdt-devel** package to install. Try to install id.

**Comment by gzliudan** [comment]
After install systemtap-sdt-devel, the problem is gone! Thank you very much.

**Comment by lain0** [comment]
For ubuntu this missing packet is systemtap-sdt-dev
