### ISSUE TITLE
OPERATOR % Already Exists in Postgresql 9.6.5

### ISSUE THREAD

**Issue by poppingtonic** [postgrespro/rum#29]
I installed RUM in a newly released version of postgresql 9.6, which appears to have added  an operator '%'. This seems to conflict with an operator defined in RUM, because when I run 

```
CREATE EXTENSION rum;
```

I get the error in the title.

**Comment by akorotkov** [comment]
Hmm, there is no "anyarray % anyarray" in PostgreSQL 9.6 core.  Probably it's created by another extension.  Could you show "\do+ %" output in psql for your installation?
Anyway you can create rum extension in another schema.
```sql
CREATE SCHEMA myschema;
CREATE EXTENSION rum SCHEMA myschema;
SET search_path = myschema, public, pg_catalog;
```

**Comment by poppingtonic** [comment]
I know where this is coming from. The `%` operator comes from [smlar](https://github.com/poppingtonic/smlar), which I cloned from Teodor Sigaev's website, hoping to use it for `TF-IDF`. It appears that `RUM` will eventually support TF-IDF, so should I remove `smlar` from my installation?

**Comment by akorotkov** [comment]
Yes, RUM will eventually support TF-IDF.  But I can't promise you any deadline for now.  You should decide whether you should remove smlar or more it to another schema according to your current needs.

**Comment by poppingtonic** [comment]
OK. Thank you so much. In that case, I think I'll remove smlar, eventually. For now, I'll go with the schema route.
