### ISSUE TITLE
clang  warns about unused variable in rum_ts_utils.c

### ISSUE THREAD

**Issue by jmscott** [postgrespro/rum#3]
clang warns about the unused variable 'extra_data' at line 722 in rum_ts_utils.c.  adding a void cast of extra_data will safely silence the warning.

  (void)extra_data

or just remove the declaration of 'extra_data'.

**Comment by select-artur** [comment]
Thank you for the issue! It was fixed.

Repository was updated. A lot of changes were done. For example, operator <-> was renamed to <=>, index is built faster.

**Comment by jmscott** [comment]
will test today ... on a 6 million page database.

thanks for the hard work-john

**Comment by select-artur** [comment]
Excellent!
I close the issue.

**Comment by jmscott** [comment]
do i only rebuild the rum indexes?

**Comment by select-artur** [comment]
For better testing you also need uninstall extension from your database with built indexes (because rum introduce new operators and operator classes now). After that quit psql (if you use it). Then:
- build extension from sources
- install extension to your database
- build index.
