### ISSUE TITLE
server process  was terminated when create tsquery index using rum

### ISSUE THREAD

**Issue by fengkai9** [postgrespro/rum#30]
Hi,
I am trying to create tsquery index.
`CREATE TABLE query (q tsquery, tag text);`
`insert into query (q,tag) values('(AA|BB|CC|DD|FF|GGGG)&(HH|II|JJ|KK|LL|MM|NN)&!(XXX|YYY|ZZZ|ABC)','sn');`
`create index query_idx on query using rum(q);`
server process   was terminated by signal 11: Segmentation fault.
`server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.`

When i am trying to insert
`insert into query (q,tag) values('(AA|BB|CC|DD|FF|GGGG)&(HH|II|JJ|KK|LL|MM|NN)&!(XXX|YYY|ZZZ)','sn');`
it works well.
My Postgresql version is 10.1 & 9.6.

**Comment by akorotkov** [comment]
Hi!
Thank you for reporting.  I've managed to reproduce this issue.  Will try to fix this ASAP.

**Comment by akorotkov** [comment]
Could you recheck this case on 73864069?

**Comment by fengkai9** [comment]
It's fixed, thank you @akorotkov .
