### ISSUE TITLE
Does rum index support parallel query?

### ISSUE THREAD

**Issue by LoveTommy** [postgrespro/rum#33]

**Comment by za-arthur** [comment]
Do you mean parallel index scan? `RUM` doesn't support it yet. As far as I know only `btree` index supports parallel index scan.

**Comment by LoveTommy** [comment]
Do you have large dataset to test rum performance?

**Comment by za-arthur** [comment]
Yes, take the dump file [pglist-28-04-16.dump.gz](http://www.sai.msu.su/~megera/postgres/files/pglist-28-04-16.dump.gz). You need to decompress it and load via psql, for example.
You can see queries from the slides [Better Full Text Search in PostgreSQL ](https://www.slideshare.net/ArthurZakirov1/better-full-text-search-in-postgresql) started from 10th page.
