### ISSUE TITLE
Does rum support LIKE operation?

### ISSUE THREAD

**Issue by LoveTommy** [postgrespro/rum#34]

**Comment by za-arthur** [comment]
`RUM` doesn't support LIKE operator for now. It is possible to create an additional opclass for that, but there is no such opclass yet. You can try prefix search, if it is suitable for you:
```sql
$ select * from test_table where tsv @@ to_tsquery('english', 'tes:*');
```

**Comment by LoveTommy** [comment]
thank you!, I create an additional opclass for that like pg_trgm. when the strategy == 3 that means it is LIKE operation，then key->recheckCurItem = true; but it does not work.

**Comment by za-arthur** [comment]
You can check out [vgram](https://github.com/akorotkov/vgram). It is an opclass for GIN and is developed by @akorotkov .

**Comment by ArturFormella** [comment]
I have the similar question - is there any way to speedup this kind of query?

```SQL
CREATE TABLE test_rum(description tsvector, symbols text);
CREATE INDEX rumidx1 ON test_rum USING rum(description rum_tsvector_ops);
CREATE INDEX rumidx2 ON test_rum USING gin(symbols gin_trgm_ops);

INSERT INTO test_rum(t) 
VALUES ( to_tsvector('high current rectifier diode'), '1n4003-DIO 1n4003-SMD 1n4003-THT');

Query: "diode rectifier 1N4003"

SELECT * FROM test_rum WHERE
  (description @@ 'rectifier' or symbols LIKE '%rectifier%' )
  AND
  (description @@ 'diode' or symbols LIKE '%diode%' )
  AND
  (description @@ '1N4003' or symbols LIKE '%1N4003%' )
```

**Comment by akorotkov** [comment]
@ArturFormella, this query should be accelerated by scanning both GIN and RUM and combination of BitmapAND and BitmapOR.  But that would be done on the executer level, and it would be rather slower than if it would be executed entirely in GIN or in RUM.  So, we eventually need RUM support for pg_trgm indexes...

**Comment by LoveTommy** [comment]
@akorotkov  I create an additional opclass for LIKE operator, and in rum_tsquery_consistent function I add these codes : if (strategy == 3) *recheck = true;

**Comment by ArturFormella** [comment]
@LoveTommy, could you share your SQL code?
