### ISSUE TITLE
RUM use GENERIC WAL

### ISSUE THREAD

**Issue by zl785998063** [postgrespro/rum#37]
Hello 

I find that rum use `generic WAL`, generates too big `WAL`traffic. can I use `internal WAL` function to `WAL`.

Thanks

**Comment by za-arthur** [comment]
Hello,
Indeed generic WAL generates a lot WAL traffic. Unfortunately extensions cannot use internal WAL functions, they can use only generic WAL. There is a patch [Generic WAL compression](https://www.postgresql.org/message-id/flat/59F90ABF.2060407@postgrespro.ru#59F90ABF.2060407@postgrespro.ru), which allow to generate less WAL traffic, but it is not commited yet.

**Comment by zl785998063** [comment]
Hello,

I used the patch to test my case, I find that ,the insert time takes more time and the WAL's size did't change.
before, my insert time about 600s ,now it takes 1800s. the function  computeRegionDelta(generic_xlog.c) takes  about 90% time. Have you met this situation.and did you have any ideas about this situation?
BTW, I use `gprof ` to test the time consuming.

Thanks

**Comment by za-arthur** [comment]
Developer of the patch is Oleg and I haven't tested the patch yet. It will be great if you share your results in the thread "Generic WAL compression" mentioned above.
