### ISSUE TITLE
Could you tell me the formula for document relevance?

### ISSUE THREAD

**Issue by postgresmith** [postgrespro/rum#38]
I'm testing your rum. I've learned the structure of your index. But I do not understand the function "rum_ts_distance_tt", I want to know what you are based on the principle of calculation. Could you tell me?

**Comment by za-arthur** [comment]
Relevance is distance between a document and a query. So closer the distance to zero the better relevancy.

**Comment by FireFoxPlus** [comment]
I also want to know the formula. As you say:"So closer the distance to zero the better relevancy", how can I define two sentence are similar by using rum_ts_distance? Distance is less than 2 or something else?  If I know the formula, I can define similar as I need.

**Comment by za-arthur** [comment]
I didn't understand your use case completely. If you want to search similar texts you may want to use pg_trgm extension.
rum_ts_distance shows distance between a document and a query, not between two sentences.
