### ISSUE TITLE
rum support postgre10 ?

### ISSUE THREAD

**Issue by normandie199** [postgrespro/rum#39]
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/13691976/35469896-219a6824-037a-11e8-9a71-a41bb8d322c7.png">

**Comment by normandie199** [comment]
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/13691976/35469902-35cbd6d4-037a-11e8-930e-36d68677448a.png">

**Comment by normandie199** [comment]
how to resolve the issues?

**Comment by za-arthur** [comment]
Hello,
RUM supports PostgreSQL 9.6 and 10. Did you compile the extension by yourself? Or maybe you got it as a package from somewhere?
