### ISSUE TITLE
 inconsistent results for queries against a table with and without rum indexes

### ISSUE THREAD

**Issue by jmscott** [postgrespro/rum#4]
i am getting inconsistent results for queries against a table with and without rum indexes.
i've tested under isolated builds of pg9.6beta3 on both mac and linux. a temporary zip demonstrating the issue is here:

   http://setspace.com/~jmscott/rumbug-060ebdc.zip

also,  can tsqueries be indexed?  i ask because under on linux (not mac)  i see this error during regress.

ERROR:  Indexing of phrase tsqueries isn't supported yet

could this be related to the inconsistent queries?  i do not see the error on macos 10.11.6.

**Comment by select-artur** [comment]
Thank you!
Fixed in eaffea730265c2fc3a85e7b229b87a5610ab88f1 commit.

**Comment by jmscott** [comment]
excellent.  version 0700d5d  passes on max 10.11.6.

**Comment by select-artur** [comment]
Nice. I closed the issue.
