### ISSUE TITLE
installcheck many failures when pg server guc "exit_on_error=true"

### ISSUE THREAD

**Issue by jmscott** [postgrespro/rum#56]
installcheck fails with many errors for a pg server with the guc "exit_on_error=true".
perhaps the installcheck scripts could set exit_on_error=true?  i tested under fedora
4.19.10-300.fc29.x86_64.

**Comment by za-arthur** [comment]
Hello,
Do you use a `RUM` package or do you build it by yourself? Also can you write what version of RUM and PostgreSQL do you use?

**Comment by za-arthur** [comment]
Can you send errors log too?
