### ISSUE TITLE
Status of TODO-item: Improve GENERIC WAL to support shift

### ISSUE THREAD

**Issue by andreak** [postgrespro/rum#64]
Is this supported now in PG-12?
If not, are there any plans to implement it for pg-13?

**Comment by za-arthur** [comment]
Hi @andreak ,

Unfortunately the improvement isn't commited yet. See:
https://www.postgresql.org/message-id/flat/59F90ABF.2060407%40postgrespro.ru

And I'm not sure that it will be commited in pg 13, because we have lack of resources right now.

**Comment by andreak** [comment]
Ok
