### ISSUE TITLE
using rum for columns with very long text

### ISSUE THREAD

**Issue by ghost** [postgrespro/rum#65]
hi 

i am thinking of using rum instead of gin but was wondering if it has the same 1Mb limitation as when i try to index my column with gin i get this error:
CREATE INDEX desc_text_idx ON table USING GIN (to_tsvector('english', Desc_Text))
ERROR: string is too long for tsvector (1076204 bytes, max 1048575 bytes)

Thank you.

**Comment by sokolcati** [comment]
Hi!

The error occurs not because of the GIN index, but because of to_tsquery(). The 1MB limit is a limitation of the tsquery type.

If you want to avoid such a limitation, pay attention to the tsquery2 type: https://github.com/postgrespro/tsvector2
