### ISSUE TITLE
when pg

### ISSUE THREAD

**Issue by miaojianxin** [postgrespro/rum#82]

**Comment by miaojianxin** [comment]
bad work

**Comment by obartunov** [comment]
On Fri, Apr 3, 2020 at 6:05 AM miaojianxin <notifications@github.com> wrote:
>
> bad work

what does it mean ?

>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
Postgres Professional: http://www.postgrespro.com
The Russian Postgres Company
