### ISSUE TITLE
Can it support postgresql 9.5.4 ?

### ISSUE THREAD

**Issue by killerwzb** [postgrespro/rum#92]
Hi:
   I build rum with postgresql 9.5.4 ,but get a error following like this：
[wzbwangzhibin@iZ2vcdckpocdm6q53dl4onZ rum]$ make USE_PGXS=1
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -g -lpthread -fpic -I. -I./ -I/home/wzbwangzhibin/tongdb/include/postgresql/server -I/home/wzbwangzhibin/tongdb/include/postgresql/internal -D_GNU_SOURCE -I/usr/include/libxml2   -c -o src/rumsort.o src/rumsort.c
In file included from src/rumsort.c:27:0:
src/rum.h:15:26: fatal error: access/amapi.h: No such file or directory
 #include "access/amapi.h"
                          ^
compilation terminated.
make: *** [src/rumsort.o] Error 1

Can you tell me how to build it with postgresql 9.5.4?

**Comment by df7cb** [comment]
Fwiw, the version requirement needs to be bumped further. Currently, README.md says
```
Before build and install **rum** you should ensure following:

* PostgreSQL version is 9.6+.
```

But now it should be 11+ since 10 raises this error:
```
16:17:50 gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fno-omit-frame-pointer -g -O2 -ffile-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I. -I./ -I/usr/include/postgresql/10/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/mit-krb5  -c -o src/rumsort.o src/rumsort.c
16:17:50 In file included from src/rumsort.c:41:
16:17:50 src/tuplesort10.c: In function ‘tuplesort_begin_heap’:
16:17:50 src/tuplesort10.c:785:77: error: macro "TRACE_POSTGRESQL_SORT_START" requires 6 arguments, but only 5 given
16:17:50   785 |                                                                 randomAccess);
16:17:50       |                                                                             ^
```
